// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB759OXmm8SowaPv-dgIAkUwOUcHA94gI',
    appId: '1:649915008702:web:f0ca625721e72e898e00ef',
    messagingSenderId: '649915008702',
    projectId: 'lettersquared-c1603',
    authDomain: 'lettersquared-c1603.firebaseapp.com',
    storageBucket: 'lettersquared-c1603.appspot.com',
    measurementId: 'G-RNQPDCV8TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARde5VkL7yRL5z2_PzyQHa-rhmwexrIcI',
    appId: '1:649915008702:android:4c6821d9bb40dbce8e00ef',
    messagingSenderId: '649915008702',
    projectId: 'lettersquared-c1603',
    storageBucket: 'lettersquared-c1603.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDjSs8SbZL0Bb307PmY0h_5L3bOj9gaWk',
    appId: '1:649915008702:ios:f5f1f85533a7db458e00ef',
    messagingSenderId: '649915008702',
    projectId: 'lettersquared-c1603',
    storageBucket: 'lettersquared-c1603.appspot.com',
    iosBundleId: 'com.example.lettersquared',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDjSs8SbZL0Bb307PmY0h_5L3bOj9gaWk',
    appId: '1:649915008702:ios:f5f1f85533a7db458e00ef',
    messagingSenderId: '649915008702',
    projectId: 'lettersquared-c1603',
    storageBucket: 'lettersquared-c1603.appspot.com',
    iosBundleId: 'com.example.lettersquared',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB759OXmm8SowaPv-dgIAkUwOUcHA94gI',
    appId: '1:649915008702:web:f42c0dc33a36aed88e00ef',
    messagingSenderId: '649915008702',
    projectId: 'lettersquared-c1603',
    authDomain: 'lettersquared-c1603.firebaseapp.com',
    storageBucket: 'lettersquared-c1603.appspot.com',
    measurementId: 'G-6QLQ2M4TKZ',
  );
}
